# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

pool:
  vmImage: Ubuntu latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(System.DefaultWorkingDirectory)/*.csproj'
    arguments: '--output $(System.DefaultWorkingDirectory)/publish_output --configuration Release'
    
 
- task: ArchiveFiles@2
  displayName: 'Archive FIles'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output/'
    includeRootFolder: false
    # archiveType: zip
    # archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    # replaceExistingArchive: true
 
# - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#   artifact: drop
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'JacMar service principal'
    appType: 'functionApp'
    appName: 'jacmarDevOpsCs'
    package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    # package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
    deploymentMethod: 'zipdeploy'
    
